<a href="https://colab.research.google.com/github/Katie-Moses/DSPS_KMoses/blob/main/labs/earthquake_data_munching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
earthquakes = pd.read_csv("https://raw.githubusercontent.com/fedhere/DSPS_FBianco/refs/heads/main/data/earthquakes.csv",sep=r"\s+")

In [4]:
earthquakes.shape

(70798, 13)

In [5]:
earthquakes.head()

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
0,1984/01/01,01:30:57.52,eq,l,2.02,c,33.246,-116.433,1.6,C,28255,13,17
1,1984/01/01,05:31:34.16,eq,l,2.12,c,32.945,-116.295,5.4,C,28259,18,42
2,1984/01/01,06:59:05.14,eq,l,2.43,c,33.343,-117.628,5.6,C,28260,13,30
3,1984/01/01,11:10:25.29,eq,l,2.07,c,33.668,-116.780,13.8,C,28270,19,40
4,1984/01/01,19:38:19.79,eq,l,2.13,c,33.963,-116.290,2.7,C,28553,40,49

In [6]:
earthquakes.tail()

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
70793,2002/12/29,19:37:24.56,eq,l,2.21,l,35.31400,-118.66767,3.7,A,9874709,25,948
70794,2002/12/29,20:17:33.40,eq,l,2.02,l,35.32133,-118.66000,1.8,A,9874745,48,245
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [7]:
earthquakes.describe()

,MAG,LAT,LON,DEPTH,EVID,NPH,NGRM
count,70798.000000,70798.000000,70798.00000,70798.000000,7.079800e+04,70798.000000,70798.000000
mean,2.417826,33.977749,-116.88145,5.707677,3.699163e+06,30.424376,175.725049
std,0.407683,1.156586,1.07667,3.842620,3.495378e+06,22.374143,226.196774
min,2.000000,30.094830,-121.76000,0.000000,2.825500e+04,0.000000,0.000000
25%,2.120000,33.061000,-117.69200,3.100000,7.380962e+05,15.000000,59.000000
50%,2.300000,34.056750,-116.59000,5.300000,3.049477e+06,24.000000,111.000000
75%,2.590000,34.591000,-116.25100,6.900000,3.325926e+06,39.000000,211.000000
max,7.100000,37.985500,-113.71900,29.300000,3.736673e+07,406.000000,3815.000000

In [8]:
earthquakes.M

0        c
1        c
2        c
3        c
4        c
        ..
70793    l
70794    l
70795    l
70796    l
70797    l
Name: M, Length: 70798, dtype: object

In [9]:
earthquakes.columns

Index(['#YYY/MM/DD', 'HH:mm:SS.ss', 'ET', 'GT', 'MAG', 'M', 'LAT', 'LON',
       'DEPTH', 'Q', 'EVID', 'NPH', 'NGRM'],
      dtype='object')

In [10]:
earthquakes = earthquakes[['#YYY/MM/DD', 'HH:mm:SS.ss', 'MAG']]

In [11]:
earthquakes.dtypes

#YYY/MM/DD      object
HH:mm:SS.ss     object
MAG            float64
dtype: object

In [12]:
[0,1]
#{"v1":0,"v2":1}

mydictionary = {"v1":0,"v2":1}
mydictionary["v1"]

0

In [13]:
earthquakes.rename({"#YYY/MM/DD":"date","HH:mm:SS.ss":"time","MAG":"mag"},axis=1,inplace=True)

In [14]:
earthquakes.describe()

                mag
count  70798.000000
mean       2.417826
std        0.407683
min        2.000000
25%        2.120000
50%        2.300000
75%        2.590000
max        7.100000

In [15]:
pd.to_datetime("2002/12/29"+" "+"01:30:57.52")

Timestamp('2002-12-29 01:30:57.520000')

In [16]:
earthquakes["newdate"] = earthquakes["date"].map(pd.to_datetime)

In [18]:
earthquakes["datetime"] = earthquakes["date"] + " " + earthquakes["time"]
earthquakes["datetime"]

0        1984/01/01 01:30:57.52
1        1984/01/01 05:31:34.16
2        1984/01/01 06:59:05.14
3        1984/01/01 11:10:25.29
4        1984/01/01 19:38:19.79
                  ...
70793    2002/12/29 19:37:24.56
70794    2002/12/29 20:17:33.40
70795    2002/12/29 20:21:28.73
70796    2002/12/30 21:51:52.55
70797    2002/12/30 23:38:49.79
Name: datetime, Length: 70798, dtype: object

In [19]:
earthquakes["newdatetime"] = earthquakes["datetime"].map(pd.to_datetime)

DateParseError: second must be in 0..59: 1984/08/09 04:48:60.00, at position 0

In [21]:
for i in earthquakes.index:
  if earthquakes.loc[i, "time"].endswith("60.00"):
    print(earthquakes.loc[i,"time"])
    earthquakes.loc[i,"time"] = earthquakes.loc[i,"time"][:6] + "59.99"
    print(earthquakes.loc[i,"time"])

04:48:60.00
04:48:59.99
14:19:60.00
14:19:59.99
21:48:60.00
21:48:59.99
15:34:60.00
15:34:59.99
06:41:60.00
06:41:59.99

In [22]:
earthquakes["datetime"] = earthquakes["date"] + " " + earthquakes["time"]
earthquakes["newdatetime"] = earthquakes["datetime"].map(pd.to_datetime)
earthquakes["newdatetime"]

0       1984-01-01 01:30:57.520
1       1984-01-01 05:31:34.160
2       1984-01-01 06:59:05.140
3       1984-01-01 11:10:25.290
4       1984-01-01 19:38:19.790
                  ...
70793   2002-12-29 19:37:24.560
70794   2002-12-29 20:17:33.400
70795   2002-12-29 20:21:28.730
70796   2002-12-30 21:51:52.550
70797   2002-12-30 23:38:49.790
Name: newdatetime, Length: 70798, dtype: datetime64[ns]

In [23]:
earthquakes.describe()

,mag,newdate,newdatetime
count,70798.000000,70798,70798
mean,2.417826,1992-11-07 16:14:28.092318976,1992-11-08 04:14:59.083973376
min,2.000000,1984-01-01 00:00:00,1984-01-01 01:30:57.520000
25%,2.120000,1988-05-05 00:00:00,1988-05-05 20:49:20.964999936
50%,2.300000,1992-07-18 00:00:00,1992-07-18 06:27:56.530000
75%,2.590000,1996-10-29 00:00:00,1996-10-29 15:31:47.564999936
max,7.100000,2002-12-30 00:00:00,2002-12-30 23:38:49.790000
std,0.407683,NaN,NaN

In [24]:
earthquakes["newdatetime"].mean()

Timestamp('1992-11-08 04:14:59.083973376')

In [25]:
earthquakes["newdatetime"].std()

Timedelta('1826 days 19:14:43.046994976')

In [26]:
earthquakes['newdatetime'].diff()

0                          NaT
1       0 days 04:00:36.640000
2       0 days 01:27:30.980000
3       0 days 04:11:20.150000
4       0 days 08:27:54.500000
                 ...
70793   0 days 00:00:30.140000
70794   0 days 00:40:08.840000
70795   0 days 00:03:55.330000
70796   1 days 01:30:23.820000
70797   0 days 01:46:57.240000
Name: newdatetime, Length: 70798, dtype: timedelta64[ns]